# 2019년 9월 20일

## Axios 에러 핸들링 인터셉터

HTTP 통신 라이브러리인 Axios에서 제공하는 인터셉터 기능을 활용하면, `then` 또는 `catch` 블럭으로 요청과 응답이 넘어가기 전에 가로채어 원하는 작업을 수행할 수 있다. 나는 다음 두 가지 용도로 인터셉터를 사용하고 있었다.

1. API 로그 전송
2. 서버에서 401 응답을 던져주는 경우에 토큰 재발급

```javascript
axios.interceptors.response.use((response) => {
    sendApiLog();

    return response;
  }, (error) => {
    if (error.response && error.response.status === 401) {
      redirectToOAuthUrl();
    }

    return error;
  });
```

이 과정에서 내가 실수했던 부분은 `axios.interceptors.response.use`에 두 번째 인자로 전달한 에러 핸들러였다. 이 함수는 상태 코드가 2XX 이외의 값일 경우에 실행되는데, 위 코드를 보면 그냥 단순히 `error` 객체를 반환하도록 처리하고 있다. 이렇게 할 경우 실제 API를 호출하는 함수 내의 `try ~ catch` 블럭에서 실행 흐름이 `catch` 블럭으로 넘어가지 않아서 에러를 적절히 처리하기 힘들어지는 문제가 발생한다. 적절한 응답을 받지 못 했을 경우에 `catch` 블럭으로 실행 흐름을 옮기기 위해서는 단순히 인자로 들어온 `error`를 그대로 반환하는 것이 아니라 `Promise.reject(error)`를 반화하도록 해줘야 한다. 이에 따라 코드를 아래와 같이 수정했다.

```javascript
axios.interceptors.response.use((response) => {
    sendApiLog();

    return response;
  }, (error) => {
    if (error.response && error.response.status === 401) {
      redirectToOAuthUrl();
    }

    return Promise.reject(error);
  });
```
